on:
  workflow_call:
    secrets:
      github-user:
        required: true
        description: "The github login to use for the test."

      github-token:
        required: true
        description: "The github token to use for the test."


jobs:
  test-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Login with the specified credentials
        run: |
          echo "https://${{ secrets.github-user }}:${{ secrets.github-token }}@github.com" > ~/.git-credentials
          git config --global credential.helper store --file=~/.git-credentials

          echo "//npm.pkg.github.com/:_authToken=${{ secrets.github-token }}" >> ~/.npmrc

      - name: Install
        run: npm install

      - name: Run tests
        run: npm test